{"name": "test_locked_out_user_shows_error", "status": "failed", "statusDetails": {"message": "AssertionError: Locked out user should see an error\nassert ('')", "trace": "driver = <appium.webdriver.webdriver.WebDriver (session=\"79fe6ef3d71f8209a809502ba6085fbd53da1e5a\")>\n\n    def test_locked_out_user_shows_error(driver):\n        lp = LoginPage(driver)\n        lp.login(\"locked_out_user\", \"secret_sauce\")\n        err = lp.get_error()\n>       assert err and len(err) > 0, \"Locked out user should see an error\"\nE       AssertionError: Locked out user should see an error\nE       assert ('')\n\ntests\\test_invalid_login.py:8: AssertionError"}, "attachments": [{"name": "screenshot-android", "source": "3f70a516-9b5d-4299-a8e4-94e95661d7ad-attachment.png", "type": "image/png"}], "start": 1757862496838, "stop": 1757862508245, "uuid": "8e15f1d7-6c3c-42a8-9d00-19311cf6f4d7", "historyId": "42377a4218ac8a25fd3755815d980eaa", "testCaseId": "42377a4218ac8a25fd3755815d980eaa", "fullName": "tests.test_invalid_login#test_locked_out_user_shows_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_invalid_login"}, {"name": "host", "value": "DB-L-174"}, {"name": "thread", "value": "8152-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_invalid_login"}], "titlePath": ["tests", "test_invalid_login.py"]}