{"uuid": "2ae64f46-4801-434a-84a9-764fa725814d", "children": ["2e86642f-512a-4cb1-bc04-37642b374c38"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "RuntimeError: Failed to create driver for android: Message: [BROWSERSTACK_INVALID_APP_URL] The app_url/ custom_id/ shareable_id specified in the 'app' capability in your test script is invalid. Please update the 'app' capability with a valid value and try again. Refer to this document to reset the app capabilities : https://www.browserstack.com/docs/app-automate/appium/set-up-tests/specify-app#BrowserStack_SDK\n\n", "trace": "  File \"C:\\projects\\mobile-demo\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"C:\\projects\\mobile-demo\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^\n  File \"C:\\projects\\mobile-demo\\.venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\projects\\mobile-demo\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\projects\\mobile-demo\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1196, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\projects\\mobile-demo\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 923, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\projects\\mobile-demo\\conftest.py\", line 93, in driver\n    raise RuntimeError(f\"Failed to create driver for {platform}: {e}\")\n"}, "start": 1757859260852, "stop": 1757859263641}], "start": 1757859260852, "stop": 1757859263887}