{"name": "test_locked_out_user_shows_error", "status": "broken", "statusDetails": {"message": "_pytest.fixtures.FixtureLookupError: ('driver', <FixtureRequest for <Function test_locked_out_user_shows_error>>)", "trace": "file C:\\projects\\mobile-demo\\tests\\test_invalid_login.py, line 4\n  def test_locked_out_user_shows_error(driver):\nE       fixture 'driver' not found\n>       available fixtures: anyio_backend, anyio_backend_name, anyio_backend_options, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, free_tcp_port, free_tcp_port_factory, free_udp_port, free_udp_port_factory, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory\n>       use 'pytest --fixtures [testpath]' for help on them.\n\nC:\\projects\\mobile-demo\\tests\\test_invalid_login.py:4"}, "start": 1758099092822, "stop": 1758099092822, "uuid": "b49b1bff-bc0d-4832-a62b-a26f9346ff01", "historyId": "c4547e0766d6c604f1234a91c62fda1f", "testCaseId": "42377a4218ac8a25fd3755815d980eaa", "fullName": "tests.test_invalid_login#test_locked_out_user_shows_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_invalid_login"}, {"name": "host", "value": "DB-L-174"}, {"name": "thread", "value": "268-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_invalid_login"}]}