{"name": "test_locked_out_user_shows_error", "status": "failed", "statusDetails": {"message": "AssertionError: Locked out user should see an error\nassert ('')", "trace": "driver = <appium.webdriver.webdriver.WebDriver (session=\"116ff3c0fdc75c717faeccca3504f07c0531bfd2\")>\n\n    def test_locked_out_user_shows_error(driver):\n        lp = LoginPage(driver)\n        lp.login(\"locked_out_user\", \"secret_sauce\")\n        err = lp.get_error()\n>       assert err and len(err) > 0, \"Locked out user should see an error\"\nE       AssertionError: Locked out user should see an error\nE       assert ('')\n\ntests\\test_invalid_login.py:8: AssertionError"}, "attachments": [{"name": "screenshot-android", "source": "77cee2cd-026b-4f53-8752-5f48e0f4c4c6-attachment.png", "type": "image/png"}], "start": 1757858626050, "stop": 1757858634631, "uuid": "0e14cbee-069b-452b-acc2-af71ee8ef63a", "historyId": "42377a4218ac8a25fd3755815d980eaa", "testCaseId": "42377a4218ac8a25fd3755815d980eaa", "fullName": "tests.test_invalid_login#test_locked_out_user_shows_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_invalid_login"}, {"name": "host", "value": "DB-L-174"}, {"name": "thread", "value": "15608-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_invalid_login"}], "titlePath": ["tests", "test_invalid_login.py"]}